export const SITE = {
    name: 'TingleTap',
    tagline: 'Tingle, Tap, Talk',
    url: 'https://tingletap.com',
    description: "TingleTap is India's #1 free real-time chat platform — trusted by users worldwide. Join live chat rooms, send private messages, make voice & video calls, share GIFs, and connect with people across India and the globe — free forever.",
    ogImage: 'https://tingletap.com/tingletap-logo.jpg',
    ogImageAlt: "TingleTap — Free Chat Rooms, Voice & Video Calls",
    twitterHandle: '@tingletaps',
    locale: 'en_IN',
    language: 'en-IN',
    themeColor: '#7c3aed',
    author: 'TingleTap — Adrashtra Inc.',
    social: {
        instagram: 'https://www.instagram.com/tingletap',
        facebook:  'https://www.facebook.com/share/18uwA1Ybpd/',
        twitter:   'https://x.com/tingletaps',
        youtube:   'https://youtube.com/@tingletaps',
        linkedin:  'https://www.linkedin.com/in/tingle-tap-b8aa38253',
        threads:   'https://www.threads.com/@tingletap',
    },
};

// ── Keyword Banks ─────────────────────────────────────────────────────────────

// India — primary audience (city-specific + regional + general)
const KW_INDIA = [
    // Core brand & product
    'TingleTap', 'Tingle Tap', 'TingleTap chat', 'TingleTap app', 'TingleTap India',
    'Indian chat app', 'Indian chat platform', 'best chat app India', 'best chat site India',
    'free chat app India', 'free chatting India', 'free online chat India',
    'live chat rooms India', 'online chat India free', 'chat online India',
    'chat with strangers India', 'random chat India', 'Indian chat website free',
    'chat website India', 'chat site India', 'Indian chat community',
    'desi chat rooms', 'desi chat app', 'desi chat India', 'desi chatting',
    'desi social network', 'desi talk online', 'online mitra chat',
    // City-specific
    'Delhi chat room', 'Delhi chat online', 'Mumbai chat online', 'Mumbai chat room',
    'Bangalore chat', 'Bengaluru chat room online', 'Chennai chat online', 'Chennai chat room',
    'Hyderabad chat room', 'Kolkata chat online', 'Pune chat room', 'Ahmedabad chat online',
    'Jaipur chat room', 'Lucknow chat online', 'Surat chat room', 'Patna chat online',
    'Bhopal chat room', 'Indore chat', 'Chandigarh chat room', 'Nagpur chat online',
    'Visakhapatnam chat', 'Coimbatore chat room', 'Kochi chat online', 'Thiruvananthapuram chat',
    'Guwahati chat room', 'Ranchi chat online', 'Bhubaneswar chat', 'Vadodara chat',
    // Language/regional
    'Hindi chat room online', 'Hindi chat online free', 'Hinglish chat room',
    'Tamil chat room online', 'Telugu chat online free', 'Bengali chat room',
    'Gujarati chat online', 'Marathi chat room', 'Punjabi chat online',
    'Urdu chat room', 'Malayalam chat online', 'Kannada chat room', 'Odia chat online',
    'Bhojpuri chat room', 'Rajasthani chat online',
    // Voice & calls
    'voice chat India', 'free voice chat India', 'audio chat India',
    'video call India free', 'free video call online India', 'voice calling app India free',
    'online call India free', 'internet call India',
    // Social & discovery
    'chat without registration India', 'chat online without login India',
    'chat bina registration India', 'anonymous chat India', 'safe chat room India',
    'online dost banana', 'online friends India free', 'Indian random chat website',
    'talk to strangers India free', 'meet new people online India free',
    'social chat India', 'make friends online India',
    // Feature terms
    'live chat platform India', 'real-time chat India', 'free Indian chatrooms',
    'chatting website India 2025', 'chatting website India 2026',
    'best chatting app India 2025', 'best chatting app India 2026',
    'India ka best chat app', 'free chatting site India no sign up',
    'chat rooms India no registration', 'Indian dating chat', 'Indian friendship chat',
].join(', ');

// Global & NRI diaspora
const KW_GLOBAL = [
    // NRI by region
    'desi chat USA', 'Indian chat USA', 'NRI chat USA', 'Indian Americans chat',
    'desi chat UK', 'Indian chat UK', 'British Indian chat', 'Indians in UK chat',
    'desi chat Canada', 'Indian chat Canada', 'desi chat Toronto', 'Indian chat Vancouver',
    'desi chat Australia', 'Indian chat Australia', 'desi chat Sydney', 'desi chat Melbourne',
    'Indian chat New Zealand', 'desi chat Auckland',
    'desi chat UAE', 'Indian chat UAE', 'NRI chat Dubai', 'Indian chat Dubai',
    'Indian expat chat Dubai', 'Indians in UAE chat free',
    'Indian chat Saudi Arabia', 'desi chat Riyadh', 'desi chat Jeddah',
    'Indian chat Qatar', 'desi chat Doha',
    'Indian chat Kuwait', 'Indian chat Bahrain', 'Indian chat Oman',
    'Indian chat Singapore', 'desi chat Singapore', 'Indians in Singapore chat',
    'Indian chat Malaysia', 'desi chat Kuala Lumpur',
    'Indian chat South Africa', 'Indian chat Mauritius',
    'Indian chat Germany', 'desi chat Frankfurt', 'Indian chat Berlin',
    'Indian chat Netherlands', 'Indian chat France', 'Indian chat Italy',
    'Indian chat Ireland', 'Indians in Ireland chat',
    'desi chat Europe', 'Indian chat Europe free',
    // South Asian broad
    'NRI chat app', 'Indian diaspora chat', 'South Asian chat app',
    'desi chat abroad', 'Indian community chat worldwide',
    'Hindustani chat online', 'Hindi speaking community worldwide',
    'desi social media free', 'Indian social network free',
    'Pakistani chat app', 'Bangladeshi chat room online', 'Sri Lankan chat online',
    'South Asian community online', 'global desi community chat',
    // Generic global chat terms
    'free online chat rooms worldwide', 'chat with strangers online free',
    'online chat rooms 2025', 'online chat rooms 2026',
    'free online chat no registration', 'meet people online free',
    'random chat online free', 'free live chat rooms no login',
    'talk to strangers online free', 'make new friends online free',
    'global chat rooms free', 'international chat rooms',
    'free social chat platform', 'online communication platform free',
].join(', ');

// Brand + direct feature keywords
const KW_BRAND = [
    'TingleTap', 'Tingle Tap', 'TingleTap chat', 'TingleTap app', 'TingleTap India',
    'TingleTap free', 'TingleTap signup', 'TingleTap login', 'TingleTap join',
    'TingleTap rooms', 'TingleTap voice', 'TingleTap video', 'TingleTap coins',
    'TingleTap RJ', 'TingleBot', 'Adrashtra Inc chat', 'TingleTap community',
    'free chat rooms', 'live chat rooms free', 'public chat rooms free',
    'private messaging app free', 'voice chat rooms free', 'video call app free',
    'GIF chat', 'sticker chat', 'animated stickers chat', 'emoji reaction chat',
    'coin gifting chat', 'virtual gift chat app', 'RJ radio show chat',
    'broadcast chat app', 'voice broadcast online', 'premium chat app India',
    'custom username chat', 'chat app no download', 'chat app without download',
    'PWA chat app', 'progressive web app chat',
].join(', ');

// Feature-specific keywords (deep)
const KW_FEATURES = [
    // Voice & Broadcast
    'RJ radio show online India', 'live radio broadcast India', 'voice broadcast chat',
    'broadcast stage podcast India', 'mini podcast online India', 'live call-in show India',
    'internet radio show India', 'online radio host India', 'RJ platform India free',
    // Translation
    'real-time auto translation chat', 'multilingual chat room India',
    'auto translate messages chat', 'Hindi English translation chat',
    'chat in any language India', 'language barrier free chat', 'translate chat messages',
    // Safety & Moderation
    'AI moderation chat safe', 'TingleBot automod', 'safe chat room India',
    'anti-spam chat India', 'moderated chat India', 'verified chat platform India',
    'device fingerprint chat security', 'IP ban chat security',
    // Gifts & Economy
    'virtual gifts chat India', 'coin gifting chat app', 'send virtual gifts online',
    'chat gifts online India', 'earn coins chat app', 'RJ earnings platform India',
    'chat leaderboard India', 'gift economy chat',
    // Privacy
    'private encrypted messaging India', 'end-to-end encrypted chat India',
    'secure private chat India', 'encrypted DM chat app',
    // Media
    'voice message chat app India', 'audio message send online',
    'GIF sticker chat room', 'YouTube share chat room',
    'video embed chat room', 'waveform voice message chat',
    // Profile
    'custom username chat', 'username gradient chat', 'dark mode chat app India',
    'theme chat app India', 'premium chat customization', 'profile chat app India',
    // Access
    'anonymous guest chat India', 'chat without account India',
    'chat without sign up India', 'chat without login India',
    'guest chat India no registration',
].join(', ');

// Long-tail conversational & AI search queries
const KW_LONGTAIL = [
    'best free chat app in India without download',
    'how to chat online free in India',
    'free online chatting with strangers India no registration',
    'chat rooms India no login required',
    'Indian chat website without sign up 2025',
    'Indian chat website without sign up 2026',
    'which is the best chat app for Indians',
    'how to make Indian friends online for free',
    'free voice chat with strangers India',
    'best desi chat platform for NRI',
    'Indian chat community free online no registration',
    'online chatting site India without registration',
    'free live chatroom India no download',
    'how to find Indian chat rooms online',
    'chat with real Indians online free',
    'best app to chat with Indian people',
    'free chat rooms India mobile browser',
    'chat site India without login 2025 2026',
    'best social chat India 2025 2026',
    'safe online chat rooms India for adults',
    'Indian chatting website free 2025 2026',
    'how to start chatting online India',
    'free online friends India no download',
    'best Hindi chat room online free',
    'live chat India no download needed',
    'desi chat no registration required',
    'free talking with strangers India',
    'Indian chat platform with voice calls free',
    'chat with Indians for free worldwide',
    'top rated chat app India 2025',
    'top rated chat app India 2026',
    'NRI chat platform free no registration',
    'free group chat India no download',
    'Indian community chat no sign up',
    'online chat website India live 2025',
    'real time chat India free mobile',
    'desi chat room mobile no download',
    'how to talk to Indians online for free',
    'join Indian chat community free',
    'best website to chat with Indians',
    'chat with desi people online free',
    'online chatting India without phone number',
    'India chat app without verification',
    'best free talking app India',
].join(', ');

// Hindi romanized keywords (how Indians search in Roman script)
const KW_HINDI = [
    'free mein chat karo', 'bina download chat', 'online baat karna free',
    'Hindi mein chat karo', 'Indian dost banana online', 'online yaar milega',
    'free chat karna hai', 'live chat karo free', 'India ka best chatting app',
    'bina registration ke chat', 'bina login ke baat karo', 'online mil ke baat karo',
    'chat karne ki website', 'chat karne ka app', 'free baat karo online',
    'India mein online chat', 'desi chat website', 'desi app free',
    'Hindi walo se baat karo', 'Hindustani chat online free',
    'free online milna julna', 'naye dost banana online India',
].join(', ');

// ── Page configs ──────────────────────────────────────────────────────────────

export const PAGES = {
    home: {
        title: "TingleTap — India's #1 Free Chat App | Live Chat Rooms, Voice & Video Calls",
        description: "Join TingleTap — India's most vibrant free chat platform, loved by Indians worldwide. Live chat rooms, private messaging, voice & video calls, RJ radio shows, GIF sharing, auto translation. Connect with India and the global desi community. 100% free, no download required.",
        keywords: [KW_INDIA, KW_GLOBAL, KW_BRAND, KW_FEATURES, KW_LONGTAIL, KW_HINDI].join(', '),
        canonical: 'https://tingletap.com/',
        robots: 'index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1',
        ogType: 'website',
    },
    landing: {
        title: "TingleTap — India's #1 Free Chat App | Live Chat Rooms, Voice & Video Calls",
        description: "Join TingleTap — India's most vibrant free chat platform, loved by Indians worldwide. Live chat rooms, private messaging, voice & video calls, RJ radio shows, GIF sharing, auto translation. Connect with India and the global desi community. 100% free, no download required.",
        keywords: [KW_INDIA, KW_GLOBAL, KW_BRAND, KW_FEATURES, KW_LONGTAIL, KW_HINDI].join(', '),
        canonical: 'https://tingletap.com/',
        robots: 'index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1',
        ogType: 'website',
    },
    about: {
        title: "About TingleTap — India's Free Chat Platform Built for Indians Worldwide",
        description: "TingleTap is India's #1 free real-time chat platform — built by Indians for Indians everywhere. Discover our story, mission, and features: live chat rooms, RJ radio shows, voice broadcasts, auto translation, TingleBot AutoMod, and virtual gifts. Used across India, USA, UK, UAE, Canada, and 50+ countries.",
        keywords: [
            'about TingleTap', 'TingleTap story', 'TingleTap mission', 'TingleTap vision',
            'Indian chat platform mission', 'Adrashtra Inc', 'who made TingleTap',
            'TingleTap built India', 'TingleTap founders', 'TingleTap features list',
            'best Indian chat community about', 'TingleTap global community',
            'NRI chat community platform', 'desi app worldwide story',
            'India chat platform origin', 'TingleTap technology stack',
            'TingleTap safety features', 'TingleTap privacy about',
            'TingleTap for Indians abroad', 'TingleTap made in India',
            'Indian social chat platform history', 'TingleTap contact email',
            KW_BRAND, KW_INDIA,
        ].join(', '),
        canonical: 'https://tingletap.com/about',
        robots: 'index, follow, max-snippet:-1, max-image-preview:large',
        ogType: 'website',
    },
    contact: {
        title: "Contact TingleTap — Get Support, Report Issues & Reach Our Team",
        description: "Need help with TingleTap? Contact our support team for quick assistance. Report abuse, request data deletion, ask feature questions, or send business inquiries. We support users from India, USA, UK, UAE, and worldwide. Response within 24 hours.",
        keywords: [
            'contact TingleTap', 'TingleTap support', 'TingleTap help',
            'TingleTap customer service', 'TingleTap help center',
            'report problem TingleTap', 'TingleTap email support',
            'TingleTap feedback', 'TingleTap international support',
            'TingleTap grievance officer', 'TingleTap data deletion request',
            'TingleTap abuse report', 'TingleTap contact India',
            'TingleTap contact USA UK UAE', 'chat app support India',
            'TingleTap business inquiry', 'TingleTap press contact',
            'TingleTap partnership', 'support@tingletap.com',
            KW_BRAND,
        ].join(', '),
        canonical: 'https://tingletap.com/contact',
        robots: 'index, follow, max-snippet:-1',
        ogType: 'website',
    },
    faq: {
        title: "FAQ — TingleTap Help Center | Features, Safety, Coins & Technical Guide",
        description: "Complete TingleTap FAQ: how to join chat rooms, use voice messages, send virtual gifts, understand TingleBot AutoMod, manage your account, earn coins, report users, use auto translation, and more. Your guide to TingleTap — for users in India and worldwide.",
        keywords: [
            'TingleTap FAQ', 'TingleTap help center', 'how to use TingleTap',
            'TingleTap guide', 'TingleTap tutorial India', 'TingleTap instructions',
            'TingleTap chat room help', 'TingleTap coins guide', 'TingleTap voice call help',
            'TingleTap private message help', 'TingleTap automod FAQ',
            'TingleBot FAQ', 'TingleTap translation help', 'TingleTap RJ guide',
            'TingleTap broadcast FAQ', 'TingleTap account help',
            'TingleTap tutorial UK USA', 'TingleTap NRI guide',
            'TingleTap gift coins FAQ', 'TingleTap report user FAQ',
            'TingleTap safety FAQ', 'TingleTap privacy FAQ',
            'TingleTap technical help', 'TingleTap browser support',
            'TingleTap mobile guide', 'TingleTap PWA install guide',
            'chat app FAQ India', 'Indian chat platform help',
            KW_BRAND, KW_LONGTAIL,
        ].join(', '),
        canonical: 'https://tingletap.com/faq',
        robots: 'index, follow, max-snippet:-1, max-image-preview:large',
        ogType: 'website',
    },
    terms: {
        title: "Terms of Service — TingleTap User Agreement & Community Rules",
        description: "TingleTap's Terms of Service: your rights and responsibilities, community standards, prohibited content, account policies, coin economy rules, and dispute resolution. Applicable to all users globally — compliant with Indian IT Act 2000 and IT Rules 2021.",
        keywords: [
            'TingleTap terms of service', 'TingleTap user agreement',
            'TingleTap rules', 'TingleTap community guidelines',
            'TingleTap policies', 'TingleTap terms India',
            'chat app terms India', 'global chat platform terms',
            'TingleTap terms of use', 'TingleTap legal agreement',
            'TingleTap prohibited content', 'TingleTap account policy',
            'chat platform terms India IT Act', 'Indian chat platform rules',
            'TingleTap coin terms', 'TingleTap RJ terms',
            'TingleTap terms UK USA Canada', 'TingleTap GDPR terms',
            KW_BRAND,
        ].join(', '),
        canonical: 'https://tingletap.com/terms',
        robots: 'index, follow, max-snippet:-1',
        ogType: 'website',
    },
    privacy: {
        title: "Privacy Policy — How TingleTap Protects Your Data | GDPR-Aware",
        description: "TingleTap's Privacy Policy: what data we collect, how we use it, end-to-end encryption details, data deletion rights, cookies policy, and children's privacy. GDPR-aware. Compliant with India IT Act 2000 & IT Rules 2021. Your privacy is our highest commitment.",
        keywords: [
            'TingleTap privacy policy', 'TingleTap data protection',
            'chat app privacy India', 'personal data TingleTap',
            'GDPR TingleTap', 'user privacy chat India',
            'data privacy chat app India', 'UK GDPR TingleTap',
            'TingleTap privacy India IT Act', 'TingleTap data deletion',
            'TingleTap end-to-end encryption privacy', 'TingleTap no data sale',
            'TingleTap anonymous chat privacy', 'TingleTap cookie policy',
            'TingleTap children privacy', 'TingleTap data retention',
            'chat platform GDPR compliant India', 'TingleTap user rights privacy',
            'Indian chat privacy policy IT Rules 2021', 'TingleTap grievance officer privacy',
            KW_BRAND,
        ].join(', '),
        canonical: 'https://tingletap.com/privacy',
        robots: 'index, follow, max-snippet:-1',
        ogType: 'website',
    },
    disclaimer: {
        title: "Disclaimer — TingleTap Legal Notice, Liability & Content Policy",
        description: "TingleTap's official disclaimer: limitations of liability, user-generated content policies, third-party links, accuracy of information, and legal notices for the TingleTap global chat platform — applicable worldwide.",
        keywords: [
            'TingleTap disclaimer', 'TingleTap legal notice',
            'chat platform liability', 'TingleTap terms disclaimer',
            'global chat disclaimer', 'TingleTap content disclaimer',
            'TingleTap liability limitation', 'TingleTap user content policy',
            'Indian chat platform legal', 'TingleTap third-party disclaimer',
            KW_BRAND,
        ].join(', '),
        canonical: 'https://tingletap.com/disclaimer',
        robots: 'index, follow, max-snippet:-1',
        ogType: 'website',
    },
    login: {
        title: "Login to TingleTap — Sign In & Join India's #1 Chat Community",
        description: "Sign in to TingleTap and rejoin your favourite chat rooms. Quick login with email and password. Trusted by users across India, USA, UK, UAE, and 50+ countries — free forever.",
        keywords: [
            'TingleTap login', 'sign in TingleTap', 'TingleTap account login',
            'chat app login India', 'online chat login India',
            'TingleTap sign in page', 'login Indian chat platform',
            KW_BRAND,
        ].join(', '),
        canonical: 'https://tingletap.com/login',
        robots: 'index, follow',
        ogType: 'website',
    },
    signup: {
        title: "Join TingleTap Free — Create Your Account | India's #1 Chat Platform",
        description: "Sign up for TingleTap in seconds — no credit card, no app download required. Join thousands of Indians at home and abroad already chatting, calling, and connecting for free. Create your account and get started instantly.",
        keywords: [
            'TingleTap signup', 'join TingleTap', 'create TingleTap account',
            'register TingleTap', 'free chat app signup India',
            'desi chat register', 'NRI chat signup', 'Indian chat join free',
            'TingleTap create account', 'Indian chat platform register',
            'free signup chat India', 'desi app join free',
            KW_BRAND,
        ].join(', '),
        canonical: 'https://tingletap.com/signup',
        robots: 'index, follow',
        ogType: 'website',
    },
    rooms: {
        title: "Live Chat Rooms — Explore All Rooms on TingleTap | Free Join",
        description: "Browse all live chat rooms on TingleTap. Indian rooms, desi chat, Hindi rooms, regional language rooms, and topic-based global rooms. Join free — connect with Indians and the global desi community in real-time. No download needed.",
        keywords: [
            'TingleTap chat rooms', 'live chat rooms India', 'desi chat rooms online',
            'Hindi chat rooms free', 'Indian chat rooms online no registration',
            'public chat rooms free India', 'global chat rooms free',
            'NRI chat rooms', 'Indian diaspora chat rooms online',
            'regional chat rooms India', 'Tamil chat room online free',
            'Telugu chat room online', 'Bengali chat room free',
            'Gujarati chat room', 'Marathi chat room online',
            'Punjabi chat room free', 'browse chat rooms India',
            'join Indian chat room online free', 'real-time chat room India',
            KW_INDIA, KW_BRAND,
        ].join(', '),
        canonical: 'https://tingletap.com/rooms',
        robots: 'index, follow, max-snippet:-1, max-image-preview:large',
        ogType: 'website',
    },
};
