export const SITE = {
    name: 'TingleTap',
    tagline: 'Tingle, Tap, Talk',
    url: 'https://tingletap.com',
    description: "TingleTap is India's #1 free real-time chat platform. Join live chat rooms, send private messages, make voice & video calls, share GIFs, and connect with Indians across the country — free forever.",
    ogImage: 'https://tingletap.com/tingletap-logo.jpg',
    ogImageAlt: "TingleTap — India's #1 Free Chat Platform",
    twitterHandle: '@TingleTap',
    locale: 'en_IN',
    language: 'en-IN',
    themeColor: '#7c3aed',
    author: 'TingleTap — Adrashtra Inc.',
};

export const PAGES = {
    home: {
        title: "TingleTap — India's #1 Free Chat App | Chat Rooms, Voice & Video Calls",
        description: "Join TingleTap — India's most vibrant free chat platform. Live chat rooms, private messaging, voice & video calls, GIF sharing, and premium customization. 100% free. No download required.",
        keywords: "TingleTap, Indian chat app, online chat India free, desi chat rooms, Hindi chat room online, free chatting India, live chat rooms India, voice chat India, video call India, chat with strangers India, best chat app India 2025, Indian chat community, chat online without registration India, free chat app India, online mitra chat, desi chatting, India chat platform, free voice chat India, Indian social chat",
        canonical: 'https://tingletap.com/',
        robots: 'index, follow, max-snippet:-1, max-image-preview:large',
        ogType: 'website',
    },
    landing: {
        title: "TingleTap — India's #1 Free Chat App | Chat Rooms, Voice & Video Calls",
        description: "Join TingleTap — India's most vibrant free chat platform. Live chat rooms, private messaging, voice & video calls, GIF sharing, and premium customization. 100% free. No download required.",
        keywords: "TingleTap, Indian chat app, online chat India free, desi chat rooms, Hindi chat room online, free chatting India, live chat rooms India, voice chat India, video call India, chat with strangers India, best chat app India 2025, Indian chat community",
        canonical: 'https://tingletap.com/',
        robots: 'index, follow, max-snippet:-1, max-image-preview:large',
        ogType: 'website',
    },
    about: {
        title: "About TingleTap — India's Most Vibrant Chat Community",
        description: "Learn about TingleTap — built to connect Indians through real-time chat, voice & video calls. Discover our story, mission, and why millions choose TingleTap as their favourite chat app in India.",
        keywords: "about TingleTap, TingleTap story, Indian chat platform mission, Adrashtra Inc, who made TingleTap, chat app India about, TingleTap team, TingleTap founders, best Indian chat community",
        canonical: 'https://tingletap.com/about',
        robots: 'index, follow',
        ogType: 'website',
    },
    contact: {
        title: "Contact TingleTap — Get Support & Reach Our Team",
        description: "Need help with TingleTap? Contact our support team for quick assistance. Report issues, share feedback, or ask questions — we respond within 24 hours.",
        keywords: "contact TingleTap, TingleTap support, TingleTap help, TingleTap customer service, report problem TingleTap, TingleTap email, TingleTap feedback",
        canonical: 'https://tingletap.com/contact',
        robots: 'index, follow',
        ogType: 'website',
    },
    faq: {
        title: "FAQ — How to Use TingleTap | Help Center & Common Questions",
        description: "Everything you need to know about TingleTap. How to join chat rooms, use voice & video calls, manage your profile, earn coins, report users, and more. Your complete TingleTap guide.",
        keywords: "TingleTap FAQ, TingleTap help center, how to use TingleTap, TingleTap guide, TingleTap chat room help, TingleTap coins, TingleTap voice call, TingleTap profile, TingleTap tutorial India",
        canonical: 'https://tingletap.com/faq',
        robots: 'index, follow',
        ogType: 'website',
    },
    terms: {
        title: "Terms of Service — TingleTap User Agreement",
        description: "Read TingleTap's Terms of Service. Understand your rights and responsibilities as a TingleTap user, including community standards, prohibited content, and account policies.",
        keywords: "TingleTap terms of service, TingleTap user agreement, TingleTap rules, TingleTap community guidelines, TingleTap policies",
        canonical: 'https://tingletap.com/terms',
        robots: 'index, follow',
        ogType: 'website',
    },
    privacy: {
        title: "Privacy Policy — How TingleTap Protects Your Data",
        description: "TingleTap's Privacy Policy explains what data we collect, how we use it, and how we protect your personal information. Your privacy and data security are our top priority.",
        keywords: "TingleTap privacy policy, TingleTap data protection, chat app privacy India, personal data TingleTap, GDPR TingleTap, user privacy chat India",
        canonical: 'https://tingletap.com/privacy',
        robots: 'index, follow',
        ogType: 'website',
    },
    disclaimer: {
        title: "Disclaimer — TingleTap Legal Notice & Liability Statement",
        description: "TingleTap's official disclaimer: limitations of liability, user-generated content policies, and legal notices for the TingleTap chat platform.",
        keywords: "TingleTap disclaimer, TingleTap legal notice, chat platform liability, TingleTap terms disclaimer",
        canonical: 'https://tingletap.com/disclaimer',
        robots: 'index, follow',
        ogType: 'website',
    },
    login: {
        title: "Sign In to TingleTap — Access Your Chat Account",
        description: "Sign in to your TingleTap account to join chat rooms, message friends, and connect with India's chat community. New here? Sign up free in seconds.",
        keywords: "TingleTap login, sign in TingleTap, TingleTap account access",
        canonical: 'https://tingletap.com/login',
        robots: 'noindex, nofollow',
        ogType: 'website',
    },
    signup: {
        title: "Join TingleTap Free — Create Your Account | India's Chat Platform",
        description: "Create your free TingleTap account and instantly access India's most vibrant chat rooms, private messaging, voice & video calls. Sign up in seconds — no credit card needed.",
        keywords: "TingleTap signup, register TingleTap, create account TingleTap, join TingleTap free, free Indian chat account",
        canonical: 'https://tingletap.com/signup',
        robots: 'noindex, nofollow',
        ogType: 'website',
    },
    forgotPassword: {
        title: "Reset Password — TingleTap Account Recovery",
        description: "Forgot your TingleTap password? Reset it securely in a few steps and get back to chatting with India's community.",
        keywords: "TingleTap forgot password, reset password TingleTap, account recovery",
        canonical: 'https://tingletap.com/forgot-password',
        robots: 'noindex, nofollow',
        ogType: 'website',
    },
    resetPassword: {
        title: "Set New Password — TingleTap Account Recovery",
        description: "Set a new password for your TingleTap account and get back to chatting.",
        keywords: "TingleTap reset password, set new password TingleTap",
        canonical: 'https://tingletap.com/reset-password',
        robots: 'noindex, nofollow',
        ogType: 'website',
    },
    privateApp: {
        title: "TingleTap — Chat Dashboard",
        description: "Your TingleTap chat dashboard.",
        keywords: '',
        canonical: 'https://tingletap.com/',
        robots: 'noindex, nofollow',
        ogType: 'website',
    },
};
