export const SITE = {
    name: 'TingleTap',
    tagline: 'Tingle, Tap, Talk',
    url: 'https://tingletap.com',
    description: 'TingleTap is India\'s premier real-time chat platform. Connect through public chat rooms, private messages, voice & video calls, and premium customization — all in one vibrant community.',
    ogImage: 'https://tingletap.com/tingletap-logo.jpg',
    ogImageAlt: 'TingleTap — India\'s Premier Chat Platform',
    twitterHandle: '@TingleTap',
    locale: 'en_IN',
    language: 'en',
    themeColor: '#7c3aed',
    author: 'TingleTap — Adrashtra Inc.',
};

export const PAGES = {
    home: {
        title: 'TingleTap — Tingle, Tap, Talk | India\'s Premier Chat Platform',
        description: 'Connect with India\'s most vibrant chat community on TingleTap. Enjoy public chat rooms, private messaging, voice & video calls, GIFs, and premium customization. Join free today.',
        keywords: 'TingleTap, Indian chat app, online chat India, live chat rooms, free chat platform, voice chat, video call, private messaging, public chat rooms India',
        canonical: 'https://tingletap.com/',
        robots: 'index, follow',
        ogType: 'website',
    },
    landing: {
        title: 'TingleTap — Tingle, Tap, Talk | India\'s Premier Chat Platform',
        description: 'Connect with India\'s most vibrant chat community on TingleTap. Enjoy public chat rooms, private messaging, voice & video calls, GIFs, and premium customization. Join free today.',
        keywords: 'TingleTap, Indian chat app, online chat India, live chat rooms, free chat platform, voice chat, video call, private messaging, public chat rooms India',
        canonical: 'https://tingletap.com/',
        robots: 'index, follow',
        ogType: 'website',
    },
    about: {
        title: 'About TingleTap — India\'s Most Vibrant Chat Community',
        description: 'Learn about TingleTap — the platform built to bring Indians together through real-time text, voice, and video communication. Discover our story, mission, and what makes us different.',
        keywords: 'about TingleTap, TingleTap story, Indian chat platform mission, Adrashtra Inc, who made TingleTap, chat app India about',
        canonical: 'https://tingletap.com/about',
        robots: 'index, follow',
        ogType: 'website',
    },
    contact: {
        title: 'Contact TingleTap — Get Support & Reach Our Team',
        description: 'Have questions, feedback, or need help? Contact the TingleTap team through our support channels. We\'re here to assist you 24/7 with any issues or inquiries.',
        keywords: 'contact TingleTap, TingleTap support, TingleTap help, TingleTap email, chat app customer service, report issue TingleTap',
        canonical: 'https://tingletap.com/contact',
        robots: 'index, follow',
        ogType: 'website',
    },
    faq: {
        title: 'FAQ — Frequently Asked Questions | TingleTap Help Center',
        description: 'Find answers to the most common questions about TingleTap. Learn how to join chat rooms, use voice & video calls, manage your profile, report users, and more.',
        keywords: 'TingleTap FAQ, TingleTap help, TingleTap questions, how to use TingleTap, chat room FAQ, voice call help, video call TingleTap',
        canonical: 'https://tingletap.com/faq',
        robots: 'index, follow',
        ogType: 'website',
    },
    terms: {
        title: 'Terms of Service — TingleTap User Agreement',
        description: 'Read TingleTap\'s Terms of Service. Understand your rights and responsibilities as a user of our chat platform, including community standards, prohibited content, and account policies.',
        keywords: 'TingleTap terms of service, TingleTap user agreement, chat platform terms, TingleTap rules, TingleTap policies',
        canonical: 'https://tingletap.com/terms',
        robots: 'index, follow',
        ogType: 'website',
    },
    privacy: {
        title: 'Privacy Policy — How TingleTap Protects Your Data',
        description: 'TingleTap\'s Privacy Policy explains what data we collect, how we use it, and how we protect your personal information. Your privacy matters to us.',
        keywords: 'TingleTap privacy policy, TingleTap data protection, chat app privacy, personal data TingleTap, GDPR TingleTap, user privacy chat',
        canonical: 'https://tingletap.com/privacy',
        robots: 'index, follow',
        ogType: 'website',
    },
    disclaimer: {
        title: 'Disclaimer — TingleTap Legal Notice & Liability Statement',
        description: 'Read TingleTap\'s official disclaimer. This page outlines the limitations of liability, user-generated content policies, and legal notices for the TingleTap chat platform.',
        keywords: 'TingleTap disclaimer, TingleTap legal notice, chat platform liability, TingleTap terms disclaimer, user content disclaimer',
        canonical: 'https://tingletap.com/disclaimer',
        robots: 'index, follow',
        ogType: 'website',
    },
    login: {
        title: 'Sign In to TingleTap — Access Your Chat Account',
        description: 'Sign in to your TingleTap account to join chat rooms, send messages, and connect with friends. New here? Create your free account in seconds.',
        keywords: 'TingleTap login, sign in TingleTap, TingleTap account access',
        canonical: 'https://tingletap.com/login',
        robots: 'noindex, nofollow',
        ogType: 'website',
    },
    signup: {
        title: 'Create Your Free TingleTap Account — Join India\'s Chat Community',
        description: 'Sign up for TingleTap for free. Create your account and instantly access hundreds of Indian chat rooms, private messaging, voice & video calls, and more.',
        keywords: 'TingleTap signup, register TingleTap, create account TingleTap, join TingleTap free',
        canonical: 'https://tingletap.com/signup',
        robots: 'noindex, nofollow',
        ogType: 'website',
    },
    forgotPassword: {
        title: 'Reset Password — TingleTap Account Recovery',
        description: 'Forgot your TingleTap password? Reset it securely in just a few steps and regain access to your chat account.',
        keywords: 'TingleTap forgot password, reset password TingleTap, account recovery',
        canonical: 'https://tingletap.com/forgot-password',
        robots: 'noindex, nofollow',
        ogType: 'website',
    },
    resetPassword: {
        title: 'Set New Password — TingleTap Account Recovery',
        description: 'Set a new password for your TingleTap account to regain access and continue chatting.',
        keywords: 'TingleTap reset password, set new password TingleTap',
        canonical: 'https://tingletap.com/reset-password',
        robots: 'noindex, nofollow',
        ogType: 'website',
    },
    privateApp: {
        title: 'TingleTap — Chat Dashboard',
        description: 'Your TingleTap chat dashboard.',
        keywords: '',
        canonical: 'https://tingletap.com/',
        robots: 'noindex, nofollow',
        ogType: 'website',
    },
};
